# Generated by Django 2.2 on 2019-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='num',
            field=models.CharField(max_length=20),
        ),
    ]
