# Generated by Django 2.2 on 2019-04-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190426_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='heatmap')),
                ('index', models.SmallIntegerField()),
            ],
        ),
    ]
